'use client'

import { useState } from 'react'
import { Card } from '../../components/ui/Card'
import { Button } from '../../components/ui/Button'
import { Modal } from '../../components/ui/Modal'
import { ApprovalItem, ApprovalItemData } from '../../components/ui/ApprovalItem'
import { Clock, PartyPopper, CheckCircle2, XCircle } from 'lucide-react'

type Tab = 'pending' | 'approved' | 'rejected'

const DEMO_APPROVALS: ApprovalItemData[] = [
    {
        id: '1',
        title: 'Assign 25 members into 3 groups by ZIP code',
        type: 'group-assignment',
        summary: 'Members will be distributed across College Group, Young Adults Group, and Downtown Group based on geographic location.',
        riskFlags: [
            {
                type: 'info',
                message: 'This action will update group memberships for 25 people.',
            },
        ],
        details: {
            description: 'Part of the Fall Groups Plan workflow.',
            affectedCount: 25,
            metadata: {
                'Generated by': 'Fall Groups Plan',
                'Created at': '2 hours ago',
            },
            content: `Group Assignments:
                • College Group (ZIP 90210): 8 members
                • Young Adults Group (ZIP 90211): 10 members  
                • Downtown Group (ZIP 90212): 7 members`,
        },
    },
    {
        id: '2',
        title: 'Send SMS to 245 members: "Welcome to your new small group!"',
        type: 'message-draft',
        summary: 'Mass SMS message will be sent to all members who were assigned to fall groups.',
        riskFlags: [
            {
                type: 'warning',
                message: 'Mass messaging (>200 recipients) requires approval.',
            },
            {
                type: 'danger',
                message: 'Contains PII (phone numbers). Ensure compliance with data policies.',
            },
        ],
        details: {
        description: 'Automated welcome message for new group members.',
        affectedCount: 245,
        metadata: {
            'Generated by': 'Fall Groups Plan',
            'Message type': 'SMS',
            'Estimated cost': '$12.25',
        },
        content: `Hi [First Name]! 👋

            Welcome to your new small group: [Group Name]!

            Your group leader, [Leader Name], will reach out soon with meeting details.

            We're excited to have you connected!

            - The Team at Trellis Church`,
        },
    },
    {
        id: '3',
        title: 'Update "Fall Kickoff Event" with 52 new registrants',
        type: 'event-update',
        summary: 'Add recently imported contacts to the Fall Kickoff Event registration list.',
        riskFlags: [],
        details: {
            description: 'Bulk event registration from Google Sheets import.',
            affectedCount: 52,
            metadata: {
                'Event date': 'October 15, 2025',
                'Current registrants': '148',
                'New total': '200',
            },
        },
    },
]

export default function ApprovalsPage() {
    const [activeTab, setActiveTab] = useState<Tab>('pending')
    const [pendingItems, setPendingItems] = useState<ApprovalItemData[]>(DEMO_APPROVALS)
    const [approvedItems, setApprovedItems] = useState<ApprovalItemData[]>([])
    const [rejectedItems, setRejectedItems] = useState<ApprovalItemData[]>([])
    const [selectedItem, setSelectedItem] = useState<ApprovalItemData | null>(null)
    const [modalOpen, setModalOpen] = useState(false)

    const handleApprove = (id: string) => {
        const item = pendingItems.find((i) => i.id === id)
        if (item) {
            setPendingItems((prev) => prev.filter((i) => i.id !== id))
            setApprovedItems((prev) => [...prev, item])
        }
    }

    const handleReject = (id: string) => {
        const item = pendingItems.find((i) => i.id === id)
        if (item) {
            setPendingItems((prev) => prev.filter((i) => i.id !== id))
            setRejectedItems((prev) => [...prev, item])
        }
    }

    const handleViewDetails = (id: string) => {
        const item = pendingItems.find((i) => i.id === id)
        if (item) {
            setSelectedItem(item)
            setModalOpen(true)
        }
    }

    const getCurrentItems = () => {
        switch (activeTab) {
            case 'pending':
                return pendingItems
            case 'approved':
                return approvedItems
            case 'rejected':
                return rejectedItems
        }
    }

    const currentItems = getCurrentItems()

    return (
        <main className="min-h-screen px-6 pt-32 pb-20">
            <div className="w-full max-w-5xl mx-auto">
                {/* Header */}
                <header className="mb-8">
                    <h1 className="mb-2 text-4xl font-bold text-white">Approvals</h1>
                    <p className="text-lg text-white/70">
                        Review and confirm Trellis&rsquo;s suggested actions before they go live.
                    </p>
          {pendingItems.length > 0 && (
            <div className="flex items-center gap-2 px-4 py-2 mt-4 border rounded-lg bg-yellow-400/10 border-yellow-400/30 w-fit">
              <Clock className="w-6 h-6 text-yellow-400" />
              <p className="font-medium text-yellow-300">
                {pendingItems.length} {pendingItems.length === 1 ? 'action' : 'actions'} require
                your review
              </p>
            </div>
          )}
                </header>

            {/* Tabs */}
            <div className="flex gap-2 mb-6">
                <TabButton
                    active={activeTab === 'pending'}
                    onClick={() => setActiveTab('pending')}
                    count={pendingItems.length}
                >
                    Pending
                </TabButton>
                <TabButton
                    active={activeTab === 'approved'}
                    onClick={() => setActiveTab('approved')}
                    count={approvedItems.length}
                >
                    Approved
                </TabButton>
                <TabButton
                    active={activeTab === 'rejected'}
                    onClick={() => setActiveTab('rejected')}
                    count={rejectedItems.length}
                >
                    Rejected
                </TabButton>
            </div>

            {/* Items List */}
            <div className="space-y-4">
          {currentItems.length === 0 ? (
            <Card padding="lg" className="text-center">
              <div className="py-12">
                <div className="flex justify-center mb-4">
                  {activeTab === 'pending' ? (
                    <PartyPopper className="w-16 h-16 text-green-400" />
                  ) : activeTab === 'approved' ? (
                    <CheckCircle2 className="w-16 h-16 text-green-400" />
                  ) : (
                    <XCircle className="w-16 h-16 text-red-400" />
                  )}
                </div>
                            <h3 className="mt-4 text-2xl font-bold text-white">
                                {activeTab === 'pending'
                                    ? "All caught up!"
                                    : activeTab === 'approved'
                                    ? 'No approved items yet'
                                    : 'No rejected items'}
                            </h3>
                            <p className="mt-2 text-white/60">
                                {activeTab === 'pending'
                                    ? 'There are no pending approvals at the moment.'
                                    : activeTab === 'approved'
                                    ? 'Approved items will appear here.'
                                    : 'Rejected items will appear here.'}
                            </p>
                        </div>
                    </Card>
                ) : (
                    currentItems.map((item) => (
                        <ApprovalItem
                            key={item.id}
                            item={item}
                            onApprove={handleApprove}
                            onReject={handleReject}
                            onViewDetails={handleViewDetails}
                        />
                    ))
                )}
            </div>

            {/* Details Modal */}
            <Modal
            isOpen={modalOpen}
            onClose={() => setModalOpen(false)}
            title={selectedItem?.title || ''}
            >
            {selectedItem && (
                <div className="space-y-6">
                {/* Description */}
                <div>
                    <h4 className="mb-2 text-sm font-semibold text-white/60">Description</h4>
                    <p className="text-white">{selectedItem.details?.description}</p>
                </div>

                {/* Metadata */}
                {selectedItem.details?.metadata && (
                    <div>
                    <h4 className="mb-2 text-sm font-semibold text-white/60">Details</h4>
                    <div className="space-y-2">
                        {Object.entries(selectedItem.details.metadata).map(([key, value]) => (
                        <div key={key} className="flex justify-between">
                            <span className="text-white/60">{key}:</span>
                            <span className="font-medium text-white">{value}</span>
                        </div>
                        ))}
                    </div>
                    </div>
                )}

                {/* Content */}
                {selectedItem.details?.content && (
                    <div>
                    <h4 className="mb-2 text-sm font-semibold text-white/60">
                        {selectedItem.type === 'message-draft' ? 'Message Content' : 'Details'}
                    </h4>
                    <div className="p-4 font-mono text-sm text-white whitespace-pre-wrap rounded-lg bg-white/5">
                        {selectedItem.details.content}
                    </div>
                    </div>
                )}

              {/* Actions in Modal */}
              <div className="flex flex-wrap gap-3 pt-4 border-t border-white/10">
                <Button
                  onClick={() => {
                    handleApprove(selectedItem.id)
                    setModalOpen(false)
                  }}
                  size="lg"
                >
                  <CheckCircle2 className="inline-block w-5 h-5 mr-2" />
                  Approve
                </Button>
                <Button
                  onClick={() => {
                    handleReject(selectedItem.id)
                    setModalOpen(false)
                  }}
                  variant="outline"
                  size="lg"
                >
                  <XCircle className="inline-block w-5 h-5 mr-2" />
                  Reject
                </Button>
                    <Button onClick={() => setModalOpen(false)} variant="ghost" size="lg">
                    Close
                    </Button>
                </div>
                </div>
            )}
            </Modal>
            </div>
        </main>
    )
}

function TabButton({
    active,
    onClick,
    children,
    count,
}: {
    active: boolean
    onClick: () => void
    children: React.ReactNode
    count?: number
}) {
    return (
        <button
            onClick={onClick}
            className={`px-6 py-3 rounded-full font-medium transition-all ${
                active
                ? 'bg-white text-black'
                : 'bg-white/5 text-white border border-white/20 hover:bg-white/10'
            }`}
        >
        {children}
        {count !== undefined && count > 0 && (
            <span
            className={`ml-2 px-2 py-0.5 rounded-full text-xs ${
                active ? 'bg-black/10' : 'bg-white/10'
            }`}
            >
                {count}
            </span>
        )}
        </button>
    )
}

